/**
 * Centralized Permission Catalog for Qershi-Link Core Banking System.
 * Corresponds 1:1 with backend database permissions in master_schema / tenant schemas.
 * Standard format: RESOURCE_ACTION (all underscores).
 */
export const PERMISSIONS = {
  // --- Member Profile Management ---
  MEMBER_CREATE: 'MEMBER_CREATE',
  MEMBER_VIEW_BASIC: 'MEMBER_VIEW_BASIC',
  MEMBER_VIEW_FULL: 'MEMBER_VIEW_FULL',
  KYC_VERIFY: 'KYC_VERIFY',
  NEXT_OF_KIN_VIEW: 'NEXT_OF_KIN_VIEW',
  NEXT_OF_KIN_MANAGE: 'NEXT_OF_KIN_MANAGE',

  // --- Account & Deposit Management ---
  ACCOUNT_VIEW: 'ACCOUNT_VIEW',
  ACCOUNT_VIEW_ALL: 'ACCOUNT_VIEW_ALL',
  ACCOUNT_CREATE: 'ACCOUNT_CREATE',
  ACCOUNT_OPEN: 'ACCOUNT_OPEN',
  ACCOUNT_APPROVE: 'ACCOUNT_APPROVE',
  ACCOUNT_FREEZE: 'ACCOUNT_FREEZE',
  ACCOUNT_LIEN: 'ACCOUNT_LIEN',
  LIEN_CREATE: 'LIEN_CREATE',
  LIEN_RELEASE: 'LIEN_RELEASE',
  LIEN_VIEW: 'LIEN_VIEW',
  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_MANAGE: 'PRODUCT_MANAGE',
  SACCO_CONFIG: 'SACCO_CONFIG',
  BRANCH_VIEW: 'BRANCH_VIEW',
  BRANCH_MANAGE: 'BRANCH_MANAGE',

  // --- Pricing & Fee Engine ---
  TARIFF_VIEW: 'TARIFF_VIEW',
  TARIFF_MANAGE: 'TARIFF_MANAGE',
  PRICING_VIEW: 'TARIFF_VIEW',
  PRICING_MANAGE: 'TARIFF_MANAGE',

  // --- Banking Operations (Cash Desk, Tills & Transfers) ---
  CASH_DEPOSIT: 'CASH_DEPOSIT',
  TRANSACTION_DEPOSIT: 'TRANSACTION_DEPOSIT',
  SAVINGS_WITHDRAW: 'SAVINGS_WITHDRAW',
  TRANSACTION_WITHDRAW: 'TRANSACTION_WITHDRAW',
  MEMBER_TRANSFER: 'TRANSFER_EXECUTE',
  TRANSACTION_TRANSFER: 'TRANSACTION_TRANSFER',
  TRANSFER_EXECUTE: 'TRANSFER_EXECUTE',
  TRANSACTION_VIEW: 'TRANSACTION_VIEW_ALL',
  TRANSACTION_VIEW_ALL: 'TRANSACTION_VIEW_ALL',
  TELLER_TILL_VIEW: 'TELLER_TILL_VIEW',
  TELLER_TILL_MANAGE: 'TELLER_TILL_MANAGE',

  // --- General Ledger & Financial Reporting (Day 3) ---
  COA_VIEW: 'COA_VIEW',
  COA_MANAGE: 'COA_MANAGE',
  FINANCIAL_REPORT_VIEW: 'FINANCIAL_REPORT_VIEW',

  // --- Loan Origination System (LOS) ---
  LOAN_APPLICATION_CREATE: 'LOAN_APPLICATION_CREATE',
  LOAN_APPLICATION_VIEW: 'LOAN_APPLICATION_VIEW',
  LOAN_APPLICATION_APPROVE: 'LOAN_APPLICATION_APPROVE',
  LOAN_GROUP_MANAGE: 'LOAN_GROUP_MANAGE',

  // --- Loan Management System (LMS) ---
  LOAN_ACCOUNT_VIEW: 'LOAN_ACCOUNT_VIEW',
  LOAN_DISBURSE_PROCESS: 'LOAN_DISBURSE_PROCESS',
  LOAN_REPAYMENT_PROCESS: 'LOAN_REPAYMENT_PROCESS',
  LOAN_DELINQUENCY_VIEW: 'LOAN_DELINQUENCY_VIEW',

  // --- Core Banking EOD & Batch Operations ---
  EOD_VIEW: 'EOD_VIEW',
  EOD_EXECUTE: 'EOD_EXECUTE',

  // --- Share Capital, Dividends & Standing Orders (Day 5) ---
  SHARE_CAPITAL_VIEW: 'SHARE_CAPITAL_VIEW',
  SHARE_CAPITAL_MANAGE: 'SHARE_CAPITAL_MANAGE',
  SHARE_TRANSFER_APPROVE: 'SHARE_TRANSFER_APPROVE',
  DIVIDEND_VIEW: 'DIVIDEND_VIEW',
  DIVIDEND_SIMULATE: 'DIVIDEND_SIMULATE',
  DIVIDEND_POST: 'DIVIDEND_POST',
  STANDING_ORDER_VIEW: 'STANDING_ORDER_VIEW',
  STANDING_ORDER_MANAGE: 'STANDING_ORDER_MANAGE',
  STANDING_ORDER_SWEEP: 'STANDING_ORDER_SWEEP',

  // --- Notification & Messaging Gateway Engine (Day 6) ---
  NOTIFICATION_CONFIG_MANAGE: 'NOTIFICATION_CONFIG_MANAGE',
  NOTIFICATION_TEMPLATE_MANAGE: 'NOTIFICATION_TEMPLATE_MANAGE',
  NOTIFICATION_SEND: 'NOTIFICATION_SEND',
  NOTIFICATION_LOG_VIEW: 'NOTIFICATION_LOG_VIEW',

  // --- Security, Governance & Administration ---
  USER_VIEW_ALL: 'USER_VIEW_ALL',
  USER_MANAGE: 'USER_MANAGE',
  ROLE_MANAGE: 'ROLE_MANAGE',
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
  SACCO_ATTACH: 'SACCO_ATTACH',
  REPORT_VIEW_ALL: 'REPORT_VIEW_ALL',
};

/**
 * Standard Core Banking System Roles
 */
export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SACCO_ADMIN: 'SACCO_ADMIN',
  ADMIN: 'ADMIN',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
  LOAN_OFFICER: 'LOAN_OFFICER',
  TELLER: 'TELLER',
  AUDITOR: 'AUDITOR',
  MEMBER: 'MEMBER',
};
