/**
 * Centralized Permission Catalog for Qershi-Link Core Banking System.
 * Corresponds 1:1 with backend database permissions in master_schema / tenant schemas.
 */
export const PERMISSIONS = {
  // --- Member Profile Management ---
  MEMBER_CREATE: 'MEMBER:CREATE',
  MEMBER_VIEW_BASIC: 'MEMBER:VIEW_BASIC',
  MEMBER_VIEW_FULL: 'MEMBER:VIEW_FULL',
  KYC_VERIFY: 'KYC:VERIFY',
  NEXT_OF_KIN_VIEW: 'NEXT_OF_KIN:VIEW',
  NEXT_OF_KIN_MANAGE: 'NEXT_OF_KIN:MANAGE',

  // --- Account & Deposit Management ---
  ACCOUNT_VIEW: 'ACCOUNT:VIEW',
  ACCOUNT_CREATE: 'ACCOUNT:CREATE',
  ACCOUNT_APPROVE: 'ACCOUNT:APPROVE',
  ACCOUNT_FREEZE: 'ACCOUNT:FREEZE',
  ACCOUNT_LIEN: 'ACCOUNT:LIEN',
  PRODUCT_VIEW: 'PRODUCT:VIEW',
  PRODUCT_MANAGE: 'PRODUCT:MANAGE',
  SACCO_CONFIG: 'SACCO:CONFIG',

  // --- Banking Operations (Cash Desk & Transfers) ---
  CASH_DEPOSIT: 'CASH:DEPOSIT',
  SAVINGS_WITHDRAW: 'SAVINGS:WITHDRAW',
  MEMBER_TRANSFER: 'TRANSFER:EXECUTE',
  TRANSACTION_VIEW: 'TRANSACTION:VIEW_ALL',

  // --- Loan Origination System (LOS) ---
  LOAN_APPLICATION_CREATE: 'LOAN_APPLICATION:CREATE',
  LOAN_APPLICATION_VIEW: 'LOAN_APPLICATION:VIEW',
  LOAN_APPLICATION_APPROVE: 'LOAN_APPLICATION:APPROVE',
  LOAN_GROUP_MANAGE: 'LOAN_GROUP:MANAGE',

  // --- Loan Management System (LMS) ---
  LOAN_ACCOUNT_VIEW: 'LOAN_ACCOUNT:VIEW',
  LOAN_DISBURSE_PROCESS: 'LOAN_DISBURSE:PROCESS',
  LOAN_REPAYMENT_PROCESS: 'LOAN_REPAYMENT:PROCESS',

  // --- Security, Governance & Administration ---
  USER_VIEW_ALL: 'USER:VIEW_ALL',
  USER_MANAGE: 'USER:MANAGE',
  ROLE_MANAGE: 'ROLE:MANAGE',
  AUDIT_LOG_VIEW: 'AUDIT_LOG:VIEW',
  SACCO_ATTACH: 'SACCO:ATTACH',
  REPORT_VIEW_ALL: 'REPORT:VIEW_ALL',
};

/**
 * Standard Core Banking System Roles
 */
export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SACCO_ADMIN: 'SACCO_ADMIN',
  ADMIN: 'ADMIN',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
  LOAN_OFFICER: 'LOAN_OFFICER',
  TELLER: 'TELLER',
  AUDITOR: 'AUDITOR',
  MEMBER: 'MEMBER',
};
