apiVersion: v1
kind: Secret
metadata:
  name: sacco-secrets
  namespace: sacco-core
type: Opaque
stringData:
  # 🔐 JWT Signing & Verification Key (256-bit Hex Key from repo)
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"

  # 📲 AfroMessage SMS Gateway Credentials
  # Replace the value below with your active AfroMessage API Key
  AFROMESSAGE_API_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJpZGVudGlmaWVyIjoiMmZIMjdweTJZampWMWlYNVJxMHhFeGZaZnNjd1UxM2QiLCJleHAiOjE5NDQyNDM4MzQsImlhdCI6MTc4NjQ3NzQzNCwianRpIjoiOTM5Y2MxM2EtNjQ1My00NjBlLWFhMDQtMmViZTVjY2M0ZjZlIn0.JToav9-Hvhg5VjUdFeNtBdceG-UYX0Sx7W1-7ugQTXo"
  AFROMESSAGE_API_URL: "https://api.afromessage.com/api/send"

  # 🗄️ PostgreSQL Master Credentials
  POSTGRES_DB: "qershi-link"
  POSTGRES_USERNAME: "postgres"
  POSTGRES_PASSWORD: "postgres"
