apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-management-service
  namespace: sacco-core
  labels:
    app: account-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-management-service
  template:
    metadata:
      labels:
        app: account-management-service
    spec:
      containers:
        - name: account-management-service
          image: account-management-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8082
            - name: grpc
              containerPort: 9082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/qershi-link?stringtype=unspecified"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SERVER_PORT
              value: "8082"
            - name: GRPC_SERVER_PORT
              value: "9082"
            - name: GRPC_CLIENT_PROFILE_SERVICE_ADDRESS
              value: "static://profile-service:9081"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sacco-secrets
                  key: JWT_SECRET
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_FLYWAY_TABLE
              value: "flyway_schema_history_account"
            - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseSerialGC"
          resources:
            requests:
              memory: "192Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: account-management-service
  namespace: sacco-core
  labels:
    app: account-management-service
spec:
  type: LoadBalancer
  selector:
    app: account-management-service
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: grpc
      protocol: TCP
      port: 9082
      targetPort: 9082
