apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: sacco-core
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8086
            - name: grpc
              containerPort: 9086
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/qershi-link?stringtype=unspecified"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SERVER_PORT
              value: "8086"
            - name: GRPC_SERVER_PORT
              value: "9086"
            - name: JWT_SECRET
              value: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
            - name: AFROMESSAGE_API_KEY
              value: "eyJhbGciOiJIUzI1NiJ9.eyJpZGVudGlmaWVyIjoiMmZIMjdweTJZampWMWlYNVJxMHhFeGZaZnNjd1UxM2QiLCJleHAiOjE5NDQyNDM4MzQsImlhdCI6MTc4NjQ3NzQzNCwianRpIjoiOTM5Y2MxM2EtNjQ1My00NjBlLWFhMDQtMmViZTVjY2M0ZjZlIn0.JToav9-Hvhg5VjUdFeNtBdceG-UYX0Sx7W1-7ugQTXo"
            - name: AFROMESSAGE_API_URL
              value: "https://api.afromessage.com/api/send"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 180
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: sacco-core
  labels:
    app: notification-service
spec:
  type: LoadBalancer
  selector:
    app: notification-service
  ports:
    - name: http
      protocol: TCP
      port: 8086
      targetPort: 8086
    - name: grpc
      protocol: TCP
      port: 9086
      targetPort: 9086
