apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: sacco-core
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432      # The port other services use to call it
      targetPort: 5432 # The port the Postgres pod is listening on
  type: ClusterIP      # This keeps the DB internal to your cluster (secure)