syntax = "proto3";

package com.kab.qershi.account.grpc;

option java_multiple_files = true;
option java_package = "com.kab.qershi.account.infrastructure.grpc";

// Core Banking Account Management gRPC Remote Procedures
service AccountGrpcService {
  rpc GetAccountByNo (AccountNoRequest) returns (AccountProtoResponse);
  rpc ValidateAccountForDebit (DebitValidationProtoRequest) returns (ValidationProtoResponse);
  rpc ValidateAccountForCredit (CreditValidationProtoRequest) returns (ValidationProtoResponse);
  rpc PostTransaction (PostTransactionRequest) returns (PostTransactionResponse);
}

message AccountNoRequest {
  string account_no = 1;
  string tenant_schema = 2;
}

message DebitValidationProtoRequest {
  string account_no = 1;
  string amount = 2;
  string tenant_schema = 3;
}

message CreditValidationProtoRequest {
  string account_no = 1;
  string amount = 2;
  string tenant_schema = 3;
}

message ValidationProtoResponse {
  bool is_valid = 1;
  string message = 2;
  string available_balance = 3;
}

message PostTransactionRequest {
  string account_no = 1;
  string amount = 2;
  string transaction_type = 3; // "CREDIT" or "DEBIT"
  string tenant_schema = 4;
}

message PostTransactionResponse {
  bool is_success = 1;
  string message = 2;
  string new_balance = 3;
}

message AccountProtoResponse {
  string account_id = 1;
  string account_no = 2;
  string user_id = 3;
  string sacco_code = 4;
  string branch_code = 5;
  string product_code = 6;
  string book_balance = 7;
  string lien_hold_amount = 8;
  string available_balance = 9;
  string status = 10;
  string freeze_status = 11;
  string phone_number = 12;
  string full_name = 13;
}
